# -*- coding: utf-8 -*-
"""codes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_yvfVP3JvIjZZW8tTbNVRzo9qkQ6tor

Funciones auxiliares para autoencoder
"""

# Commented out IPython magic to ensure Python compatibility.
#from google.colab import drive
#drive.mount('/gdrive')
# %cd /gdrive/My \Drive/Colab \Notebooks/miccai/
# %ls

from torch import nn as nn
import pandas as pd
import torch
import autoencoder
import os

def MSEWithLogitsLoss(output, target):
    output = nn.functional.sigmoid(output)
    loss = nn.functional.mse_loss(output,target)
    return loss

#####################################
###### cargar modelo guardado #######
#####################################

# csv_file, cada row: idModelo	ruta	conf_encoder	conf_decoder

def get_model(csv_file,index):
    
    model_root=pd.read_csv(csv_file)
    try:
        model=autoencoder.Autoencoder(model_root.iloc[index,2],model_root.iloc[index,3])
        best_model_root=model_root.iloc[index,1]
        print(os.path.join(best_model_root))
        try: 
            best_model=torch.load(os.path.join(best_model_root), map_location=torch.device('cuda'))
            state_dict=best_model['model_state_dict']
            model.load_state_dict(state_dict)
            
        except:
            print('no se pudo cargar')
              
        return model
    
    except:
        print('None')
        return None